import * as auth from "./services/auth";
import * as users from "./services/users";
import * as organizers from "./services/organizers";
import * as events from "./services/events";
import * as organizerEvents from "./services/organizerEvents";
import * as organizerRefunds from "./services/organizerRefunds";
import * as dashboard from "./services/dashboard";
import * as orders from "./services/orders";
import * as refunds from "./services/refunds";
import * as tickets from "./services/tickets";
import * as uploads from "./services/uploads";
import * as contact from "./services/contact";
import * as config from "./services/config";
import * as organizerPayoutAccount from "./services/organizerPayoutAccount";
import * as paymentMethods from "./services/paymentMethods";
import * as organizerWallet from "./services/organizerWallet";
import * as buyerWallet from "./services/buyerWallet";

export const api = { auth, users, organizers, events, organizerEvents, organizerRefunds, dashboard, orders, refunds, tickets, uploads, contact, config, organizerPayoutAccount, paymentMethods, organizerWallet, buyerWallet };

export { onSessionExpired, newIdempotencyKey } from "./client";
export { ApiError, normalizeError } from "./errors";
export { qk, USER_SCOPED_KEYS } from "./queries/keys";
export * from "./queries/paging";
export * from "./queries/auth";
export * from "./queries/users";
export * from "./queries/organizers";
export * from "./queries/events";
export * from "./queries/organizerEvents";
export * from "./queries/organizerRefunds";
export * from "./queries/dashboard";
export * from "./queries/orders";
export * from "./queries/refunds";
export * from "./queries/tickets";
export * from "./queries/uploads";
export * from "./queries/contact";
export * from "./queries/config";
export * from "./queries/organizerPayoutAccount";
export * from "./queries/paymentMethods";
export * from "./queries/organizerWallet";
export * from "./queries/buyerWallet";
export * from "./queries/gatewayAdmin";
